### ISSUE TITLE
Include version of benchmark-maps in run metadata

### ISSUE THREAD

**Issue by maxrjones** [carbonplan/benchmark-maps#31]
In order to avoid losing track of which version of the benchmark-maps created which data, it would be helpful to a version or commit for benchmark-maps in the run metadata. I think the easiest way to do this would be to move the functionality from `main.py` into `carbonplan_benchmarks` because then we could use the [package version](https://github.com/carbonplan/benchmark-maps/blob/98fcad3ef523fc1cf3e5317ce38a7e70962db224/carbonplan_benchmarks/__init__.py#L3).

For context, I moved the analysis functionality into a `carbonplan_benchmarks` package in https://github.com/carbonplan/benchmark-maps/pull/27 to make it easier to use those functions in the notebooks included in https://github.com/NASA-IMPACT/zarr-visualization-cookbook.

cc @katamartin @andersy005 for feedback on this idea

**Comment by katamartin** [comment]
At a high level, it sounds really crucial that we understand exactly how each trace was generated! This sounds like a good idea and I might even suggest that, if we're not doing this already, we annotate the data with the parameters that the script was run with.

**Comment by maxrjones** [comment]
Thanks for your thoughts on this!

> I might even suggest that, if we're not doing this already, we annotate the data with the parameters that the script was run with.

this part is currently included

**Comment by maxrjones** [comment]
I decided to go a quicker route for now in https://github.com/carbonplan/benchmark-maps/pull/33/commits/2cc0922618c600b5d2129b2b14a6c74e92c017d7 to add commit information to the metadata file rather than packaging the benchmarking utilities
